version: '3.7'

services:
  akaunting_nginx:
    build: ./nginx
    ports:
      - ${HOST_PORT}:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - app-data:/var/www/akaunting
    restart: unless-stopped

  akaunting_php:
    build: ./php
    volumes:
      - app-data:/var/www/akaunting
    restart: unless-stopped

  akaunting_db:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password

volumes:
  app-data:
  db-data:

